workspace = { members = ["syntax"] }

[package]
name = "minuet"
version = "0.0.1"
edition = "2021"

[dependencies]
bitmask-enum = "2.2"
gray-codes = "0.1"
minuet-syntax = { path = "syntax" }
thiserror = "1.0"

[dev-dependencies]
