workspace = { members = ["syntax", "tracer"] }

[package]
name = "minuet"
version = "0.0.1"
edition = "2021"

[dependencies]
gray-codes = "0.1"
minuet-syntax = { path = "syntax" }
minuet-tracer = { path = "tracer" }
thiserror = "1.0"

[dev-dependencies]
