[package]
name = "minuet-command"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "minuet"
path = "minuet.rs"

[dependencies]
anyhow.workspace = true
minuet-semantics = { path = "../semantics" }
minuet-syntax = { path = "../syntax" }
minuet-tracer = { path = "../tracer" }
