[package]
name = "minuet-solver"
version = "0.0.1"
edition = "2021"

[lib]
path = "solver.rs"

[dependencies]
gray-codes.workspace = true
minuet-tracer = { path = "../tracer" }
thiserror.workspace = true
